[build]
  publish = "sitemap"

[[redirects]]
  from = "/2023/*"
  to = "https://conf2023.sciwork.dev/:splat"
  force = true

[[redirects]]
  from = "/*"
  to = "https://swconf2023.netlify.app/:splat"
  status = 200
  force = true
