[build]
  base = "content/2023/"
  command = "env SITEURL=$DEPLOY_PRIME_URL make html"
  publish = "output"

[context.production]
  command = "env SITEURL=$URL make html"

[[redirects]]
  from = "/register"
  to = "https://sciwork.kktix.cc/events/sciworkconf-202312-hsinchu"
  force = true
